[package]
name = "h5t"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
h5t-core = { path = "../h5t-core" }
itertools = "0.14.0"
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
